language: node_js

node_js:
  - 10

git:
  depth: 1

branches:
  only:
    - master

cache:
  directories:
    - node_modules
  yarn: true

install:
  - yarn install

script:
  - yarn run test

after_success:
  - yarn run coveralls